apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2018-04-15T10:04:35Z
  generation: 2
  labels:
    run: report-engine
  name: report-engine
  namespace: default
  resourceVersion: "355715"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/report-engine
  uid: 66936060-4094-11e8-a80b-42010a8a0079
spec:
  replicas: 1
  selector:
    matchLabels:
      run: report-engine
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: report-engine
    spec:
      containers:
      - image: gcr.io/twitterfeedmonitor/reportengine:v1
        imagePullPolicy: IfNotPresent
        name: report-engine
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
        - containerPort: 9200
          name: elastic
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-04-15T10:04:35Z
    lastUpdateTime: 2018-04-15T10:04:35Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
